# VERSIÓN 4.O: se trataría de que el usuario ingresara previamente su nombre y sus apellidos, el nombre de su mascota, su email...
# y de lo que se trataria es que la contraseña generada no se parezca a ninguno de estos criterios previamente dados
